### ISSUE TITLE
Headers problem

### ISSUE THREAD

**Issue by albabosh** [Comcast/eel#84]
I take headers from the request & put them into curl (the upstream requires basic auth), but the upstream returns 401, despite the login&password is absolutely correct (direct connect from client to upstream works correct, if client connects to upstrem through EEL - the upstream returns 401)

**Comment by boriwo** [comment]
I just tried this example successfully:

`{{curl('GET','https://jigsaw.w3.org/HTTP/Basic/','','{"Authorization":"Basic Z3Vlc3Q6Z3Vlc3Q="}')}}`

This one has eel perform basic auth against this public test endpoint: https://jigsaw.w3.org/HTTP/

Note that headers is the 4th parameter of curl() and has to be json encoded.

You might also find the built-in test endpoint http://<eel>/test/ast useful for debugging eel expressions as you construct them.

**Comment by albabosh** [comment]
{{curl('POST', '{{prop('node_api')}}', '', '{"Authorization":"Basic bXVsdGljaGFpbnJwYzpIOHJ5U1NwNU5lRFVWc3VB1856cFlSSEFFcWl1cUFzZzk2Q0JZMw=="}')}}  gives error  "Message": "invalid json in config file config-handlers/tenant1/default.json", what is wrong here?

**Comment by albabosh** [comment]
I soved it. Should look like this {{curl('GET','https://jigsaw.w3.org/HTTP/Basic/','','{\"Authorization\":\"Basic Z3Vlc3Q6Z3Vlc3Q=\"}')}}
