### ISSUE TITLE
eval - cannot get a single value 

### ISSUE THREAD

**Issue by albabosh** [Comcast/eel#85]
When using eval function I can get a part of json document, but  cannot get a single value (it appears to be empty)

**Comment by boriwo** [comment]
Do you have a specific example? eval() lets you select maps, arrays and simple types from json documents. Example of a single value selection:

`{{eval('/foo','{"foo":"bar"}')}}`

**Comment by albabosh** [comment]
This is my case:

"Transformation": {
		"{{/result}}" : "{{eval('/result/total/qty','{{prop('noderesponse')}}')}}",
		"{{/error}}" : "{{eval('/error','{{prop('noderesponse')}}')}}",
		"{{/id}}" : "{{eval('/id','{{prop('noderesponse')}}')}}",
		"{{/check}}" : "{{eval('/','{{prop('noderesponse')}}')}}"
	},

Response:

{
"check":{
"error": null,
"id": null,
"result":{
"1Gcv7PgJX8kg2zd6SMYq2shotah9H94r7bc61s":[
{"assetref": "18-265-55833", "name": "RURT", "qty": 94}
],
"total":[
{"assetref": "18-265-55833", "name": "RURT", "qty": 94}
]
}
},
"error": "",
"id": "",
"result": ""
}

The problem: eval does not return a single value (or maybe I am doing it the wrong way)

**Comment by albabosh** [comment]
P.S. Maybe it was a bit unclear, but I need "total" quantity ("qty") from where "assetref":"18-265-55833"

**Comment by boriwo** [comment]
The data under total is not a map but and array with a single map element, so you must access the array item by its index. This should work: `{{/result/total[0]/qty}}`

**Comment by albabosh** [comment]
Thanks, that really works. But I am not sure it has index [0], is there any way to get an item with "assetref":"18-265-55833" exactly ?

**Comment by boriwo** [comment]
Yes, in a situation like this you can also pull an array element by key-value-pair present in the element. The syntax works like this: `{{/result/total[assetref=18-265-55833]/qty}}`
