### ISSUE TITLE
Is there such thing as "try..catch" ?

### ISSUE THREAD

**Issue by albabosh** [Comcast/eel#87]
I need to select a transformation based on a request value, and if there is no match there should be a special "bypass" transformation. Is it possible ?

**Comment by boriwo** [comment]
Usually you have multiple handlers in a tenant folder and the one with the strongest match will win (strongest meaning largest number of matching key-value pairs). You can also have a default handler that matches everything and use that as your "bypass" transformation.

Handler 1 - matching only foo-bar messages:

```
{
    "Name": "FooBar",
    "Info": "only match foo bar messages",
    "Active": true,
    "Match": {"foo":"bar"},
    "IsMatchByExample": true,
    "TerminateOnMatch": true,
    "Transformation": {
        "{{/foobar}}": "{{/}}"
    },
    "IsTransformationByExample": false,
    "Verb": "POST",
    "Endpoint": "http://localhost:8082"
}
```

Default handler matching everything else:

```
{
    "Name": "Default",
    "Info": "matches everything (unless already grabbed by foo-bar handler)",
    "Active": true,
    "Match": null,
    "IsMatchByExample": false,
    "TerminateOnMatch": true,
    "Transformation": {
        "{{/default}}": "{{/}}"
    },
    "IsTransformationByExample": false,
    "Verb": "POST",
    "Endpoint": "http://localhost:8082"
}
```
