### ISSUE TITLE
Multiple elements arrays howto ?

### ISSUE THREAD

**Issue by albabosh** [Comcast/eel#89]
Is there an example how to transform complex json documents with multiple elements, for example such one:

"result":[
{
"balance":{
"amount": 0,
"assets":[
{
"name": "RURT",
"assetref": "18-265-55833",
"qty": 94
}
]
},
"myaddresses":["1Gcv7PgJX8kg2zd6SMYq2shotah9H94r7bc61s"],
"addresses":["1X6XtK85XBUCs5H8m7hqzAbpmFWVJyfYeBR6C4"],
"permissions":[],
"items":[],
"data":[],
"confirmations": 22,
"blockhash": "000be156594897acd8f5e9c68249673438cf8e0d5f6f7859e0a88035f88be067",
"blockindex": 1,
"blocktime": 1530763252,
"txid": "86b933e10c91cec316fb2b0755551aafad8323e32f5cccb239a5b7f9f08ae8a6",
"valid": true,
"time": 1530763252,
"timereceived": 1530772271
},
{
"balance":{
"amount": 0,
"assets":[
{
"name": "RURT",
"assetref": "18-265-55833",
"qty": 57
}
]
},
"myaddresses":["1DfitzueRPd1j4huBat6ppQVNKY2jEsFsm9sMW"],
"addresses":["1X6XtK85XBUCs5H8m7hqzAbpmFWVJyfYeBR6C4"],
"permissions":[],
"items":[],
"data":[],
"confirmations": 11,
"blockhash": "00b531dccf9bd9332ee2d1b36a037a6eb6d1eb2d5938fdc9c7b46ee6923792d7",
"blockindex": 1,
"blocktime": 1537977604,
"txid": "9346498d4bce423e7e34589d83667ae251f5b3be8eefdb4565490761dcd7a966",
"valid": true,
"time": 1537977592,
"timereceived": 1537977592
}
],
"error": null,
"id": 2
}

**Comment by boriwo** [comment]
There's really not much difference between applying minor transformations to small payloads and major transformations to large payloads. Essentially EEL allows you to transform any JSON input to any JSON output. You should be aware of the two different syntax styles (by path and by example) described here https://github.com/Comcast/eel/blob/master/doc/handlers.md and here https://github.com/Comcast/eel/blob/master/doc/jpath.md and the various built-in functions described here https://github.com/Comcast/eel/blob/master/doc/functions.md. There's also a nice set of working examples at the end of the readme https://github.com/Comcast/eel/blob/master/README.md. If you have any specific questions / transformation challenges I'm happy to help with putting a transformation handler together.
